= 답변 받았습니다! API 명세
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:
:docinfo: shared-head

== 강의 관리

=== 모든 강의 조회 (GET /courses)
==== 성공
operation::courses/find/success[snippets='http-request,http-response']

=== 강의 추가하기 (POST /courses)
==== 성공
operation::courses/create/success[snippets='http-request,http-response']

=== 특정 강의 이름 받아오기 (GET /courses/{id}/name)
==== 성공
operation::course/get/name/success[snippets='http-request,http-response']

== 리뷰 관리
=== 특정 강의의 리뷰 보기 (GET /courses/{id}/reviews)
==== 성공
operation::reviews/find/success[snippets='http-request,http-response']
==== 실패
===== 최근 작성한 리뷰가 6개월 이상이거나, 없을경우
operation::reviews/find/fail/denied[snippets='http-request,http-response']
===== 수업이 존재하지 않을 경우
operation::reviews/find/fail/noCourse[snippets='http-request,http-response']

=== 특정 강의의 리뷰 작성하기 (POST /courses/{id}/reviews)
==== 성공
operation::reviews/create/success[snippets='http-request,http-response']

=== 리뷰 좋아요 (PUT /courses/reviews/{rid}/like)
==== 성공
operation::reviews/like/success[snippets='http-request,http-response']

=== 내 리뷰 보기 (GET /courses/reviews/me)
==== 성공
operation::reviews/find/me/success[snippets='http-request,http-response']

=== 리뷰 수정 (PUT /courses/reviews/{rid})
==== 성공
operation::reviews/update/success[snippets='http-request,http-response']

==== 실패
===== 권한이 없는 경우
operation::reviews/update/fail/noAuth[snippets='http-request,http-response']

=== 리뷰 삭제 (DELETE /courses/reviews/{rid})
==== 성공
operation::reviews/delete/success[snippets='http-request,http-response']

==== 실패
===== 권한이 없는 경우
operation::reviews/delete/fail/noAuth[snippets='http-request,http-response']

== 게시글 관리

=== 모든 게시글 보기 (GET /posts)
==== 성공
operation::post/find/all/success[snippets='http-request,http-response']

=== 특정 카테고리 게시글 보기 (GET /posts?page=1&category=free)
유효한 category 값: free(자유), question(질문), trade(중고거래), offer(구인), notice(공지)

==== 성공
operation::post/find/category/success[snippets='http-request,http-response']

=== 특정 게시글 보기 (GET /posts/{id})
==== 성공
operation::post/find/one/success[snippets='http-request,http-response']

=== 게시글 작성하기 (POST /posts)
==== 성공
operation::post/create/success[snippets='http-request,http-response']
==== 실패
===== 제목에 내용이 없는 경우
operation::post/create/fail/noTitle[snippets='http-request,http-response']

=== 내 게시글 보기 (GET /posts/me)
==== 성공
operation::post/find/me/success[snippets='http-request,http-response']

=== 게시글 좋아요 (PUT /posts/{id}/like)
==== 성공
operation::post/like/success[snippets='http-request,http-response']

=== 게시글 수정 (PUT /posts/{id})
==== 성공
operation::post/update/success[snippets='http-request,http-response']
==== 실패
===== 권한이 없는 경우
operation::post/update/fail/noAuth[snippets='http-request,http-response']
===== 제목에 내용이 없는 경우
operation::post/update/fail/noTitle[snippets='http-request,http-response']

=== 게시글 삭제 (DELETE /posts/{id})
==== 성공
operation::post/delete/success[snippets='http-request,http-response']
==== 실패
===== 권한이 없는 경우
operation::post/delete/fail/noAuth[snippets='http-request,http-response']

== 댓글 관리

=== 특정 게시글의 댓글 보기 (GET /community/{id}/comments)
==== 성공
operation::comments/find/success[snippets='http-request,http-response']

=== 특정 게시글의 댓글 작성하기 (POST /community/{id}/comments)
==== 성공
operation::comments/create/success[snippets='http-request,http-response']

=== 댓글 좋아요 (PUT /comments/{id}/like)
==== 성공
operation::comments/like/success[snippets='http-request,http-response']

=== 댓글 수정 (PUT / comments/{id})
==== 성공
operation::comments/update/success[snippets='http-request,http-response']
==== 실패
===== 권한이 없는 경우
operation::comments/update/fail/noAuth[snippets='http-request,http-response']
===== 내용이 없는 경우
operation::comments/update/fail/noContent[snippets='http-request,http-response']

=== 댓글 삭제 (DELETE /comments/{id})
==== 성공
operation::comments/delete/success[snippets='http-request,http-response']
==== 실패
===== 권한이 없는 경우
operation::comments/delete/fail/noAuth[snippets='http-request,http-response']

=== 특정 댓글의 대댓글 작성하기 (POST /comments/{id}/reply)
==== 성공
operation::reply/create/success[snippets='http-request,http-response']
==== 실패
===== 대댓글에 작성하는 경우
operation::reply/create/fail/depth[snippets='http-request,http-response']

== 신고 관리

=== 특정 게시글 신고하기 (POST /posts/{id}/report)
==== 성공
operation::posts/report/success[snippets='http-request,http-response']

=== 특정 댓글 신고하기 (POST /comments/{id}/report)
==== 성공
operation::comments/report/success[snippets='http-request,http-response']